// -------------------------------------------------------------------
// Generated by 365admin-publish 
// Service wrapper  v1
// -------------------------------------------------------------------
/*
---
title: Web deploy to production
---
*/
package cmds
import (
"context"
"encoding/json"
"os"
"path"
"github.com/nats-io/nats.go"
"github.com/nats-io/nats.go/micro"
"github.com/spf13/cobra"
"github.com/365admin/koksmat-tracing/schemas"
"github.com/365admin/koksmat-tracing/execution"
"github.com/365admin/koksmat-tracing/utils"
)
func ProvisionWebdeployproductionPost(ctx context.Context, args  []string)  ( *string, error) {

_, pwsherr := execution.ExecutePowerShell("john","*","koksmat-tracing","60-provision","10-web.ps1","" )
if (pwsherr != nil) {
	return nil,pwsherr
}
return nil, nil
	
// end result mapping

func init(){
	
}
}
